#/etc/netplan/99-config.yaml
#netplan configuration file 1 for UbuntuServerX86-64-infrastructure VM: internet, dns, dhcp
network:
        version: 2
        renderer: networkd
        ethernets:
                #internet via host
                ens33:
                        #dhcp route adds default
                        dhcp4: true
                        dhcp4-overrides:
                                use-dns: false
                        nameservers:
                                addresses: [192.168.50.1, 8.8.8.8, 1.1.1.1]  #customize this with your own internet router IP address (leave 8.8.8.8 and 1.1.1.1)
                                search: [invalid] #leave this as is
                #dns docker
                ens38:
                        #static routes, do not add gateway4 or gateway6 so that netplan does not add default route                
                        dhcp4: no
                        addresses: [192.168.25.10/24]
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [netsec-docker.isi.jhu.edu]
                #dhcp docker
                ens39:
                        #static routes, do not add gateway4 or gateway6 so that netplan does not add default route                
                        dhcp4: no
                        addresses: [192.168.25.5/24]
                        nameservers:
                                addresses: [192.168.25.10]
                                search: [netsec-docker.isi.jhu.edu]
