# Description:
#   This runtime environment example Dockerfile creates a container with a minimal Ubuntu server and suricata
# Usage:
#   From this directory, run $ sudo docker build -t tsuricata .
# By default, runs as root
# https://suricata-ids.org/
FROM ubuntu:20.04

#https://grigorkh.medium.com/fix-tzdata-hangs-docker-image-build-cdb52cc3360d
ENV TZ=US/Eastern
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN echo 'Install dependencies'
RUN apt-get update
RUN apt-get install -y net-tools wget libpcre3 libpcre3-dbg libpcre3-dev 
RUN apt-get install -y build-essential autoconf automake libtool libpcap-dev libnet1-dev libyaml-0-2 libyaml-dev 
RUN apt-get install -y zlib1g zlib1g-dev libcap-ng-dev libcap-ng0 make libmagic-dev libjansson-dev libjansson4 pkg-config
RUN apt-get install -y rustc cargo
RUN echo 'Download source code for suricata'
RUN wget "https://www.openinfosecfoundation.org/download/suricata-6.0.2.tar.gz"
RUN tar -xvzf "suricata-6.0.2.tar.gz" 
RUN echo 'Configure suricata'
RUN cd "suricata-6.0.2" && ./configure && make && make install && ldconfig

RUN echo 'Container is ready, run it using $ sudo docker run -d --name suricata --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --network bridge tsuricata'
RUN echo 'Then attach to it using $ sudo docker exec -it suricata bash'